@startuml

interface espMode<<physical button>>
interface deviceConfig<<WiFi HTTP>>
interface liveData<<BLE>>
interface api<<WiFi HTTP>>

component bGeigieNano\n {
    interface dataReports<<uart2>>
    component bGeigieController

    component <<subcomponent>>\nESP32Bee\n {
        interface IBL as "bluetoothControl"
        interface IAP as "APIControl"
        interface serverControl
        component Controller
        component ConfigServer
        component ApiConnector
        component Bluetooth
        component EspConfig

        ''' For ordering '''
        ConfigServer -[hidden]> EspConfig
        ''''''

        Controller -( serverControl
        serverControl - ConfigServer
        dataReports )- Controller
        config )-u- ConfigServer
        config -u- EspConfig
        deviceConfig -d- ConfigServer
        espMode -d- Controller
        IBL )-u- Controller
        IBL -d- Bluetooth
        IAP )-u- Controller
        IAP -d- ApiConnector
        ApiConnector -u-( config

        liveData -u- Bluetooth
        api )-u- ApiConnector
    }

    bGeigieController - dataReports

}

@enduml