@startuml

State Initializing
State Active

[*] -> Initializing

state Active {
    state SetupServer
    state ServerActive
    state StationaryMode
    state MobileMode

    state StationaryMode {
        state Connecting
        state Connected
        state Reconnecting

        [*] -> Connecting
        Connecting -> Connected : connected
        Connected -> Reconnecting : connectionLost
        Reconnecting -l-> Connected : connected

        Connecting -> MobileMode : connectFailed

    }

    Initializing -> MobileMode : setupCompleted
    Initializing -> SetupServer : [button down] setupCompleted

    SetupServer -> ServerActive : serverInitialized
    ServerActive --> MobileMode : buttonPressed
    ServerActive --> StationaryMode : startStationary

    MobileMode -> StationaryMode : buttonPressed
    StationaryMode --> MobileMode : buttonPressed
}


@enduml