@startuml


:bGeigieUser: as user
:API service: as API<<secondairy>>
:Bluetooth: as BLU<<secondairy>>
:bGeigieController: as BGN<<internal>>


rectangle <<subsystem>>\nesp32Controller{
    (Set config)
    (Set esp mode)
    (Reset)
    (Set\n mobile mode)
    (Set\n stationary mode)
    (Publish to API)
    (Publish\n over bluetooth)
    (Report data)


    (Publish to API) -u.> (Report data) : <<extend>>
    (Report data) -d.> (Publish\n over bluetooth) : <<include>>
    (Set\n mobile mode) -u-|> (Set esp mode)
    (Set\n stationary mode) -u-|> (Set esp mode)

    (Publish to API) -d- API
    (Publish\n over bluetooth) -d- BLU

    user -d- (Set esp mode)
    user -d- (Set config)
    user -d- (Reset)
    BGN -- (Report data)
}

note top of (Set config)
  Set wifi settings etc.
  - Using web interface
endnote

note top of (Set esp mode)
  Mobile mode (Just bluetooth)
  Stationary mode (Publish to API)
  - Using push button
endnote

@enduml
