@startuml


state Initializing
Initializing: action: setup ESP32
state PostInitialize
PostInitialize: entry: setWakeupTimer(3 sec)
PostInitialize: action: sleep()
state ConfigMode
state Active
state Reset
Reset: Action: reset_reading config defaults && restart system

state ConfigMode {
    state SetupConfigServer
    SetupConfigServer: entry: setLedColor(serverSetup)
    SetupConfigServer: action: initializeServer()
    state ConfigServerActive
    ConfigServerActive: entry: setLedColor(serverActive)
    ConfigServerActive: action: handleClients()
    ConfigServerActive: exit: stopServer()

    [*] --> SetupConfigServer
    SetupConfigServer --> ConfigServerActive : serverInitialized
    ConfigServerActive --> [*]
}

state Active {

    state InitActive
    InitActive: action: mode = getSavedMode()
    state MobileMode {
        state "Disconnected" as mDisconnected
        mDisconnected: entry: setLedColor(btDisconnected)
        state "Connected" as mConnected
        mConnected: entry: setLedColor(btConnected)

        [*] --> mDisconnected
        mDisconnected -> mConnected : apiReportFailed
        mConnected -> mDisconnected : apiReportSuccess
    }
    MobileMode: entry: reporter.prepare(bluetooth)

    state FixedMode {
        state Connecting
        Connecting: entry: setLedColor(connecting)
        state Operating
        Operating: entry: setLedColor(connected)
        state Error
        Error: entry: setLedColor(...)

        [*] -> Connecting
        Connecting --> Operating : apiReportSuccess
        Connecting --> Error : apiReportFailed
        Operating -> Error : apiReportFailed
        Error -> Operating : apiReportSuccess
    }
    FixedMode: entry: reporter.prepare(api, bluetooth)

    [*] --> InitActive
    InitActive --> MobileMode : [mode==mobile]
    InitActive -> FixedMode : [mode==fixed]
    MobileMode -r-> FixedMode : buttonPressed
    FixedMode -l-> MobileMode : buttonPressed

}
Active: action: reporter.run(); sleep()



[*] -> Initializing
Initializing -> PostInitialize : controllerInitialized
PostInitialize -> ConfigMode : buttonPressed
PostInitialize -d-> Active : [t > 3s]
ConfigMode -d-> Active: buttonPressed
Active --> Reset : buttonLongPressed
Reset --> [*] 

@enduml