@startuml


state Idle
state GetReading
GetReading : bGeigieConn.getReading()
state ReportReading {
    state InitBluetooth
    InitBluetooth: action: initBluetooth()
    state PublishToBluetooth
    PublishToBluetooth: action: bluetoothConnection.write(reading)
    state ReportToApi
    ReportToApi: entry: apiConnector.set(reading)
    ReportToApi: action: apiConnector.run()
    state ReportDone
    ReportDone: entry: callbackController(status)

    [*] --> InitBluetooth
    InitBluetooth --> PublishToBluetooth : bluetoothInitialized
    PublishToBluetooth --> ReportDone : readingReportedBT /status = success
    PublishToBluetooth -> ReportToApi: [in(FixedMode)] readingReportedBT

    ReportToApi --> ReportDone : readingReportedAPI /status = apiResult
    ReportDone --> [*]
}

[*] -> Idle
Idle -> GetReading : readingExpected
GetReading --> ReportReading : readingReceived
ReportReading -u-> Idle : readingReported


@enduml