@startuml


:bGeigieUser: as user
:API service: as API<<secondairy>>
:Safecast drive: as BLU<<secondairy>>
:bGeigieController: as BGN<<internal>>


rectangle <<subsystem>>\nesp32Controller{
    (Set config)
    (Set esp mode)
    (Reset configurations)
    (Set\n mobile mode)
    (Set\n fixed mode)
    (Publish to API)
    (Publish\n over bluetooth)
    (Report data)

    ''' For ordering '''
    (Set esp mode) -[hidden]> (Reset configurations)
    (Reset configurations) -[hidden]> (Set config)
    ''''''


    (Publish to API) -u.> (Report data) : <<extend>>
    (Report data) -d.> (Publish\n over bluetooth) : <<include>>
    (Set\n mobile mode) -u-|> (Set esp mode)
    (Set\n fixed mode) -u-|> (Set esp mode)

    (Publish to API) -d- API
    (Publish\n over bluetooth) -d- BLU

    user -- (Set esp mode)
    user -- (Set config)
    user -- (Reset configurations)
    BGN -- (Report data)
}

note top of (Set config)
  Set wifi settings etc.
  - Using web interface
endnote

note top of (Set esp mode)
  Mobile mode (Just bluetooth)
  Stationary mode (Publish to API)
  - Using push button
endnote

@enduml
